const P=[
/* ═══ #1 REINICIO PARASIMPÁTICO ═══
   Objetivo: Activar sistema parasimpático para restaurar función ejecutiva
   Lógica: Box breathing (4-4-4-4) → descarga cognitiva binaria → foco unidireccional
   La respiración box se mantiene DURANTE TODAS las fases como hilo conductor */
{id:1,n:"Reinicio Parasimpático",ct:"Reset",d:120,sb:"Restaura función ejecutiva",tg:"R1",cl:"#059669",int:"calma",dif:1,
ph:[{l:"Entrada Vagal",r:"0–30s",s:0,e:30,k:"Respira box: 4 dentro. 4 sostén. 4 fuera. 4 vacío.",i:"Cierra los ojos suavemente. Inhala por la nariz 4 segundos llenando el abdomen. Mantén 4 segundos sin tensión. Exhala por la boca 4 segundos vaciando completamente. Sostén vacío 4 segundos. Repite un ciclo más al mismo ritmo. Tu sistema nervioso ya está respondiendo.",sc:"Box breathing 4-4-4-4 activa complejo vagal ventral, reduce frecuencia cardíaca en 15-20s",ic:"breath",br:{in:4,h1:4,ex:4,h2:4}},
{l:"Descarga Cognitiva",r:"30–90s",s:30,e:90,k:"Identifica el peso. ¿Depende de ti? Actúa o suelta.",i:"Sin abrir los ojos, mantén la respiración box suave. Identifica el pensamiento que más pesa. Pregúntate: ¿depende de mí? Si sí, elige una micro-acción para los próximos 30 minutos. Si no, di internamente 'lo suelto'. Siente cómo el peso se alivia. Sigue respirando al mismo ritmo sin analizar — solo decide y suelta.",sc:"Decisión binaria interrumpe rumiación del córtex cingulado anterior, reduce carga del córtex prefrontal",ic:"mind",br:{in:4,h1:4,ex:4,h2:4}},
{l:"Dirección y Cierre",r:"90–120s",s:90,e:120,k:"Una acción clara. Visualízala. Abre con dirección.",i:"Mantén la respiración estable. Pregúntate: ¿cuál es la única acción que hace todo lo demás más fácil? Visualízala con detalle — qué haces, dónde, cómo. Siente la certeza. En la última exhalación, abre los ojos lentamente. Lleva esa claridad contigo.",sc:"Foco unidireccional libera dopamina hacia corteza prefrontal dorsolateral. Visualización activa vías motoras",ic:"focus",br:{in:4,h1:4,ex:4,h2:4}}]},

/* ═══ #2 ACTIVACIÓN COGNITIVA ═══
   Objetivo: Coherencia cardíaca + autorregulación emocional + enfoque dirigido
   Lógica: Ratio 6-2-8 genera coherencia → etiquetado reduce amígdala → visualización activa dopamina
   La respiración 6-2-8 se mantiene como base constante en las 3 fases */
{id:2,n:"Activación Cognitiva",ct:"Activación",d:120,sb:"Enfoque y autorregulación",tg:"AC",cl:"#6366F1",int:"enfoque",dif:1,
ph:[{l:"Coherencia Cardíaca",r:"0–30s",s:0,e:30,k:"Inhala 6. Sostén 2. Exhala 8. Fluye.",i:"Cierra los ojos. Inhala por la nariz 6 segundos expandiendo abdomen y costillas. Mantén 2 segundos con suavidad. Exhala por la boca 8 segundos como si soplaras por una pajita. Repite sin pausa. El ritmo sincroniza corazón y respiración automáticamente.",sc:"Ratio 1:1.3 genera coherencia cardíaca. Variabilidad de frecuencia cardíaca mejora en 20-30 segundos",ic:"breath",br:{in:6,h1:2,ex:8,h2:0}},
{l:"Etiquetado Emocional",r:"30–90s",s:30,e:90,k:"Nombra exactamente lo que sientes. Sin juzgar.",i:"Mantén el ritmo 6-2-8 como base. Escanea tu cuerpo. ¿Qué sientes exactamente? No 'mal' — busca la palabra precisa: ¿frustración? ¿agotamiento? ¿incertidumbre? Nombrar reduce la intensidad. Sigue respirando mientras observas cómo la emoción pierde fuerza al ser nombrada. Sin juzgar, sin resolver — solo nombra y respira.",sc:"Affect labeling reduce activación amigdalar 30-40%. Nombrar activa corteza prefrontal ventrolateral",ic:"mind",br:{in:6,h1:2,ex:8,h2:0}},
{l:"Visualización Dirigida",r:"90–120s",s:90,e:120,k:"Visualízate resolviendo. Hoy avanzo paso a paso.",i:"Sin cambiar la respiración, visualízate dentro de 2 horas habiendo completado tu tarea principal con calma. Observa tu postura, tu expresión. Di internamente: 'Hoy avanzo, paso a paso.' Repite una vez. En la próxima exhalación, abre los ojos con esa imagen clara.",sc:"Visualización prospectiva activa dopamina orientada a objetivos y reduce ansiedad anticipatoria",ic:"focus",br:{in:6,h1:2,ex:8,h2:0}}]},

/* ═══ #3 RESET EJECUTIVO ═══
   Objetivo: Descargar presión → priorizar → comprometerse con una acción
   Lógica: Exhalación larga (ratio 1:3) → filtro de urgencia → compromiso motor
   La exhalación larga se mantiene como hilo conductor de calma bajo presión */
{id:3,n:"Reset Ejecutivo",ct:"Reset",d:120,sb:"Para líderes bajo presión",tg:"RE",cl:"#059669",int:"reset",dif:1,
ph:[{l:"Descarga Rápida",r:"0–30s",s:0,e:30,k:"Inhala corto. Exhala el doble de largo. Desinfla.",i:"Cierra los ojos. Inhala por la nariz en 2 segundos. Exhala muy lento por la boca en 6 segundos — como si desinflaras un globo. Siente cómo tu cuerpo se afloja con cada exhalación larga. Repite 3 veces. Cada exhalación más lenta y profunda.",sc:"Ratio 1:3 inhalación:exhalación activa tono vagal parasimpático en menos de 20 segundos",ic:"breath",br:{in:2,h1:0,ex:6,h2:0}},
{l:"Filtro de Prioridad",r:"30–90s",s:30,e:90,k:"Tres tareas. Filtra. Solo queda una.",i:"Mantén las exhalaciones largas. Piensa en tus 3 tareas más urgentes. Para cada una: ¿es importante o solo urgente? ¿Puedo eliminarlo? ¿Delegarlo? Quédate solo con lo genuinamente importante. Confía en tu primera respuesta — sin analizar en exceso. Sigue exhalando largo mientras el ruido se despeja.",sc:"Filtro de Eisenhower conectado a estado parasimpático mejora calidad de decisiones ejecutivas",ic:"mind",br:{in:2,h1:0,ex:6,h2:0}},
{l:"Compromiso Motor",r:"90–120s",s:90,e:120,k:"Un puño cerrado. Una tarea. 60 minutos.",i:"Elige UNA tarea para los próximos 60 minutos. Solo una. Cierra el puño derecho con firmeza mientras exhalas. Di internamente: 'Los próximos 60 minutos son para esto.' Siente la decisión en tu cuerpo. Mantén 3 segundos. Suelta el puño y abre los ojos con dirección clara.",sc:"Compromiso motor ancla decisiones en memoria procedimental. Aumenta probabilidad de ejecución",ic:"focus",br:{in:2,h1:0,ex:6,h2:0}}]},

/* ═══ #4 PULSE SHIFT ═══
   Objetivo: Romper congelamiento corporal → oxigenar → liberar tensión acumulada
   Lógica: Movimiento rítmico bilateral → apertura torácica → relajación progresiva
   Transición: de movimiento activo → respiración profunda → liberación total */
{id:4,n:"Pulse Shift",ct:"Activación",d:120,sb:"Reset neurocardíaco",tg:"PS",cl:"#6366F1",int:"energia",dif:2,
ph:[{l:"Activación Rítmica",r:"0–30s",s:0,e:30,k:"Ritmo con los talones. Despierta el cuerpo.",i:"De pie o sentado, alterna elevar cada talón rítmicamente. Izquierdo. Derecho. Izquierdo. Derecho. Encuentra un ritmo constante como metrónomo. Siente cómo el movimiento sube por piernas y activa tu centro. Respira naturalmente. El ritmo bilateral despierta ambos hemisferios.",sc:"Movimiento bilateral cruza línea media corporal, activa ambos hemisferios y rompe congelamiento por estrés",ic:"body",br:null},
{l:"Apertura y Oxigenación",r:"30–90s",s:30,e:90,k:"Pecho abierto. Inhala expansión. Exhala liberación.",i:"Mantén el ritmo de talones si puedes, o detente suavemente. Lleva manos detrás de la cabeza, codos abiertos. Inhala expandiendo pecho 4 segundos. Mantén 1 segundo en máxima apertura. Exhala relajando hombros 5 segundos. Repite — cada ciclo más profundo. Tu postura se corrige. Tu oxigenación aumenta.",sc:"Apertura torácica revierte postura de estrés. Incrementa oxigenación cerebral 15-20%",ic:"breath",br:{in:4,h1:1,ex:5,h2:0}},
{l:"Liberación Progresiva",r:"90–120s",s:90,e:120,k:"Aprieta puños 3s. Suelta todo 7s. Libertad.",i:"Baja las manos. Cierra ambos puños con fuerza moderada 3 segundos mientras inhala. Siente la tensión subir por antebrazos. Suelta todo de golpe con exhalación larga de 7 segundos. Siente la ola de relajación. Repite una vez: aprieta 3s, suelta 7s. Abre los ojos con energía limpia.",sc:"Relajación progresiva de Jacobson. Contraste tensión-liberación genera relajación neuromuscular profunda",ic:"body",br:null}]},

/* ═══ #5 SKYLINE FOCUS ═══
   Objetivo: Recalibrar sistema visual-atencional → enfocar en una sola tarea
   Lógica: Visión panorámica relaja → alternancia cerca-lejos resetea → foco unidireccional
   La respiración 4-4 se mantiene suave como base en las 3 fases */
{id:5,n:"Skyline Focus",ct:"Activación",d:120,sb:"Recalibración visual-cognitiva",tg:"SF",cl:"#6366F1",int:"enfoque",dif:1,
ph:[{l:"Horizonte y Calma",r:"0–30s",s:0,e:30,k:"Mira lejos. Suaviza la mirada. Respira distancia.",i:"Busca el punto más lejano visible — ventana, cielo, horizonte. Fija la mirada sin forzar. Deja que tus ojos se relajen. Respira suavemente: inhala 4 segundos, exhala 4 segundos. Nota cómo tu respiración se calma al mirar lejos. La visión panorámica desactiva el modo de alerta.",sc:"Visión panorámica desactiva sistema de detección de amenazas (visión de túnel) y reduce activación simpática",ic:"focus",br:{in:4,h1:0,ex:4,h2:0}},
{l:"Recalibración Visual",r:"30–90s",s:30,e:90,k:"Cerca 5s. Lejos 5s. Alterna 4 veces. Recalibra.",i:"Mantén respiración 4-4. Mira tu mano a 30cm de tu cara 5 segundos. Cambia al punto más lejano 5 segundos. Alterna 4 veces sin prisa. Nota cómo tus ojos recalibran la profundidad. Sigue respirando al mismo ritmo. Deja que los ojos se ajusten naturalmente. Esto reinicia tu sistema atencional completo.",sc:"Alternancia de foco reinicia corteza parietal posterior — centro del sistema de orientación atencional",ic:"focus",br:{in:4,h1:0,ex:4,h2:0}},
{l:"Foco Láser",r:"90–120s",s:90,e:120,k:"Una tarea. Visualiza el inicio. Claridad total.",i:"Cierra los ojos. Piensa en UNA sola tarea que harás después. Visualiza exactamente cómo empiezas: dónde te sientas, qué abres, qué haces primero. Di internamente: 'Una tarea. Un resultado.' Abre los ojos en la próxima exhalación con dirección absoluta.",sc:"Foco unidireccional canaliza dopamina hacia objetivo concreto. Corteza prefrontal dorsolateral en máxima activación",ic:"focus",br:{in:4,h1:0,ex:4,h2:0}}]},

/* ═══ #6 GROUNDED STEEL ═══
   Objetivo: Generar presencia ejecutiva inquebrantable desde el cuerpo
   Lógica: Postura de poder → respiración triangular sostenida → micro-tensión de dominio
   La respiración 3-3-6 se mantiene invariable como metrónomo interno */
{id:6,n:"Grounded Steel",ct:"Protocolo",d:120,sb:"Presencia ejecutiva",tg:"GS",cl:"#0D9488",int:"calma",dif:2,
ph:[{l:"Anclaje Postural",r:"0–30s",s:0,e:30,k:"Pies firmes. Columna recta. Hombros abajo. Respira.",i:"Planta ambos pies firmemente en el suelo. Siente tu peso distribuirse. Espalda recta — como si un hilo tirara de tu coronilla. Hombros lejos de las orejas. Inhala 3 segundos. Mantén 3 segundos. Exhala 6 segundos. Repite sin alterar la postura. Tu cuerpo le dice a tu cerebro: 'Estoy seguro.'",sc:"Postura erguida suprime cortisol y eleva testosterona. Señal de seguridad al sistema nervioso autónomo",ic:"body",br:{in:3,h1:3,ex:6,h2:0}},
{l:"Ritmo Triangular",r:"30–90s",s:30,e:90,k:"3 dentro. 3 sostén. 6 fuera. Sin cambiar nada.",i:"Mantén la postura de acero. Sigue el ritmo triangular: inhala 3, sostén 3, exhala 6. Con cada ciclo sientes más control. Pies anclados. Columna recta. La exhalación larga es el doble de la inhalación — calma sin perder presencia. No cambies nada. Solo profundiza lo que ya tienes.",sc:"Ratio 1:2 inhalación:exhalación maximiza tono parasimpático manteniendo estado de alerta controlada",ic:"breath",br:{in:3,h1:3,ex:6,h2:0}},
{l:"Tensión de Dominio",r:"90–120s",s:90,e:120,k:"Core al 15%. Mantén respirando. Presencia total.",i:"Sin cambiar respiración ni postura, activa abdomen y glúteos al 15% de fuerza — solo activa, no aprietes. Mantén esta base mientras respiras. La tensión mínima te ancla completamente al presente. Cada exhalación refuerza tu presencia. Mantén hasta el final. Abre los ojos: inquebrantable.",sc:"Micro-tensión isométrica activa propioceptores de estabilidad. Genera sensación de fortaleza embodied",ic:"body",br:{in:3,h1:3,ex:6,h2:0}}]},

/* ═══ #7 HYPERSHIFT ═══
   Objetivo: Descarga emocional rápida cuando el estrés es agudo
   Lógica: Percusión vagal rompe alarma → tensión-liberación descarga músculo → exhalación larga cierra
   Transición progresiva: activo → contracción → liberación total */
{id:7,n:"HyperShift",ct:"Protocolo",d:120,sb:"Descarga emocional rápida",tg:"HS",cl:"#0D9488",int:"reset",dif:2,
ph:[{l:"Percusión Vagal",r:"0–30s",s:0,e:30,k:"Golpea suave el pecho. Siente la vibración.",i:"Yemas de los dedos sobre el esternón. Golpea suavemente a 2-3 toques por segundo. Siente la vibración propagarse por tu pecho. Respira naturalmente. Esta percusión estimula el nervio vago directamente y desactiva la alarma. Mantén el ritmo constante 30 segundos completos.",sc:"Percusión torácica estimula nervio vago por vibración mecánica directa. Desactiva respuesta de lucha-huida",ic:"body",br:null},
{l:"Contracción y Liberación",r:"30–90s",s:30,e:90,k:"Todo al 10%. Sostén 10s. Suelta 5s. Repite.",i:"Detén la percusión suavemente. Contrae TODO tu cuerpo al 10% — apenas perceptible. Manos, brazos, abdomen, piernas, mandíbula. Mantén 10 segundos respirando normalmente. Suelta completamente 5 segundos. Siente la diferencia. Repite: 10s tensión, 5s liberación. La segunda es más profunda. Tercera ronda. Cada liberación se siente como dejar caer un peso.",sc:"Relajación muscular progresiva. Cada ciclo de contracción-liberación profundiza la descarga neuromuscular",ic:"body",br:null},
{l:"Exhalación de Descarga",r:"90–120s",s:90,e:120,k:"Inhala corto 2s. Exhala largo 10s. Vacía todo.",i:"Sin tensión residual, inhala corto por la nariz 2 segundos. Exhala muy largo por la boca 10 segundos — tan lento como puedas. Cada exhalación descarga lo último de tensión. Repite 2 ciclos. La última exhalación es la más larga. Abre los ojos sintiéndote más ligero.",sc:"Ratio exhalación:inhalación 5:1 activa máximamente el sistema parasimpático de descarga profunda",ic:"breath",br:{in:2,h1:0,ex:10,h2:0}}]},

/* ═══ #8 LIGHTNING FOCUS ═══
   Objetivo: Enfoque extremo para trabajo profundo o decisiones críticas
   Lógica: Reset bilateral → fijación forzada → mantra de compromiso → integración silenciosa
   Respiración 4-6 como base constante después del reset inicial */
{id:8,n:"Lightning Focus",ct:"Activación",d:120,sb:"Enfoque extremo",tg:"LF",cl:"#6366F1",int:"enfoque",dif:3,
ph:[{l:"Reset Hemisférico",r:"0–20s",s:0,e:20,k:"Ojos izquierda-derecha rápido. 10 veces.",i:"Sin mover la cabeza, mueve tus ojos rápidamente de izquierda a derecha 10 veces. Rápido pero controlado. Esto integra ambos hemisferios y rompe patrones estancados. Respira normalmente. Al terminar, cierra los ojos un momento y nota el efecto de limpieza mental.",sc:"Movimiento ocular bilateral integra hemisferios cerebrales y desensibiliza carga emocional. Principio EMDR",ic:"focus",br:null},
{l:"Fijación de Control",r:"20–50s",s:20,e:50,k:"Un punto fijo. No parpadees. Control total.",i:"Abre los ojos. Elige un punto fijo frente a ti. Míralo sin pestañear. Cuando sientas urgencia de pestañear, resiste 2 segundos más. Respira lento: inhala 4, exhala 6. Tu corteza prefrontal está tomando control total de tu atención. Sigue fijando sin romper la mirada.",sc:"Fijación visual forzada activa masivamente corteza prefrontal dorsolateral — centro de control ejecutivo",ic:"focus",br:{in:4,h1:0,ex:6,h2:0}},
{l:"Mantra de Enfoque",r:"50–90s",s:50,e:90,k:"Aquí. Ahora. Una sola tarea. Repite con convicción.",i:"Cierra los ojos. Repite internamente: 'Aquí. Ahora. Una sola tarea.' Cada repetición más lenta, más firme. Si divaga, vuelve sin juicio. 8-10 repeticiones. Respiración: inhala 4, exhala 6. No cambies nada más. Solo repite y respira.",sc:"Mantra repetitivo elimina multitarea neural y dirige toda la energía cognitiva a un solo punto",ic:"mind",br:{in:4,h1:0,ex:6,h2:0}},
{l:"Integración Silenciosa",r:"90–120s",s:90,e:120,k:"Deja el mantra. Solo silencio. El enfoque ya está.",i:"Deja de repetir. Quédate en el silencio que creaste. Tu mente ya está enfocada — no fuerces. Si un pensamiento aparece, déjalo pasar. Respira suave: inhala 4, exhala 6. Siente la claridad. En la última exhalación, abre los ojos con dirección absoluta.",sc:"Silencio post-mantra consolida activación prefrontal en modo sostenido. Puerta al estado de flow",ic:"mind",br:{in:4,h1:0,ex:6,h2:0}}]},

/* ═══ #9 STEEL CORE RESET ═══
   Objetivo: Reinicio nervioso desde el centro corporal. Para momentos de alta presión.
   Lógica: Exhale explosivo resetea barorreceptores → core isométrico genera fuerza → alineamiento cierra
   Transición: explosivo → sostenido → calma con fuerza */
{id:9,n:"Steel Core Reset",ct:"Reset",d:120,sb:"Reinicio nervioso máximo",tg:"SC",cl:"#059669",int:"reset",dif:3,
ph:[{l:"Exhale Explosivo",r:"0–25s",s:0,e:25,k:"Llena 4s. Sostén 2s. Explota el aire. Resetea.",i:"Inhala profundo llenando abdomen 4 segundos. Mantén 2 segundos creando presión interna. Exhala EXPLOSIVAMENTE por la boca — todo el aire de golpe. Repite 3 veces. Cada explosión más fuerte. Siente el reset completo del sistema nervioso con cada ciclo.",sc:"Exhalación explosiva genera pico de presión intratorácica que resetea barorreceptores y tono autonómico",ic:"breath",br:{in:4,h1:2,ex:2,h2:0}},
{l:"Núcleo de Acero",r:"25–70s",s:25,e:70,k:"Core al 30%. Respira encima. Fuerza interior.",i:"Activa abdomen al 30% de fuerza. No contengas la respiración — respira normalmente encima de la activación. Mantén 10 segundos. Suelta 5 segundos. Repite 3 veces. Cada activación es más precisa. Siente la fuerza emocional que viene de tu centro. Esta es tu base de estabilidad.",sc:"Activación isométrica del core genera sensación de fortaleza emocional y estabiliza sistema nervioso",ic:"body",br:null},
{l:"Alineamiento Vertical",r:"70–120s",s:70,e:120,k:"Columna de acero. Respira 4-6. Presencia total.",i:"Suelta la tensión del core suavemente. Siente tu columna como una barra de acero desde el sacro hasta la coronilla. Respira: inhala 4, exhala 6. Con cada respiración la barra se solidifica. Hombros relajados pero eje fuerte. Mantén 50 segundos. Abre los ojos desde esa verticalidad inquebrantable.",sc:"Propiocepción vertical activa sistema vestibular. Genera presencia somática y confianza embodied",ic:"mind",br:{in:4,h1:0,ex:6,h2:0}}]},

/* ═══ #10 ATOMIC PULSE ═══
   Objetivo: Sincronización neurosomática mediante ritmo y atención corporal
   Lógica: Micro-pulsos activan diafragma → body scan integra → pulsación sincroniza
   Transición: respiración rítmica → atención ascendente → micro-movimiento de cierre */
{id:10,n:"Atomic Pulse",ct:"Protocolo",d:120,sb:"Sincronización neurosomática",tg:"AP",cl:"#0D9488",int:"energia",dif:2,
ph:[{l:"Pulso Respiratorio",r:"0–30s",s:0,e:30,k:"Inhala profundo. Exhala en 5 micro-pulsos.",i:"Inhala profundo 4 segundos llenando desde el abdomen. Al exhalar, hazlo en 5 micro-pulsos cortos — como si rieras sin sonido: ja-ja-ja-ja-ja. Repite 3 ciclos. Cada serie más controlada. Siente cómo el diafragma se despierta con cada micro-pulso rítmico.",sc:"Micro-pulsos espiratorios activan coordinación sensoriomotora fina del sistema respiratorio y diafragma",ic:"breath",br:{in:4,h1:0,ex:5,h2:1}},
{l:"Escaneo Ascendente",r:"30–80s",s:30,e:80,k:"Atención a los pies. Sube lento hasta la cabeza.",i:"Cierra los ojos. Lleva atención a los pies — siente el contacto con el suelo. Sube lentamente: pantorrillas, rodillas, muslos. Pausa en abdomen 3 segundos. Sube al pecho 3 segundos. Cuello, mandíbula, frente. Respira suave todo el tiempo. Cada zona recibe tu atención plena por un momento.",sc:"Body scan activa ínsula cerebral — centro de interocepción. Integra conciencia mente-cuerpo completa",ic:"mind",br:null},
{l:"Micro-Pulsación de Cierre",r:"80–120s",s:80,e:120,k:"Dedos contra pulgares. Pulsa 8 veces. Sincroniza.",i:"Cierra manos al 10% de fuerza. Genera micro-pulsos con dedos contra pulgares: 8 pulsos en 8 segundos. Descansa 2 segundos. Repite 3 veces. Ritmo constante como metrónomo. Respira naturalmente. Siente cómo la pulsación sincroniza tu sistema completo. Termina con manos abiertas y relajadas.",sc:"Ritmo somatosensorial fino genera sincronización neural global e induce estado de coherencia completa",ic:"body",br:null}]},

/* ═══ #11 QUANTUM GROUNDING ═══
   Objetivo: Anclaje profundo al presente desde la gravedad y la propiocepción
   Lógica: Respiración descendente ancla → gravedad relaja → expansión interna cierra
   Respiración 4-1-3 mantenida como hilo conductor descendente */
{id:11,n:"Quantum Grounding",ct:"Protocolo",d:120,sb:"Anclaje profundo",tg:"QG",cl:"#0D9488",int:"calma",dif:2,
ph:[{l:"Anclaje Diafragmático",r:"0–30s",s:0,e:30,k:"Diafragma abajo. Exhala hacia el suelo. Raíces.",i:"Inhala expandiendo diafragma hacia abajo 4 segundos. Mantén 1 segundo en máxima expansión. Exhala con dirección hacia abajo 3 segundos — como si empujaras el aire al suelo. Siente la solidez. Repite 3 veces, cada vez más profundo. Tu respiración te ancla como raíces.",sc:"Respiración diafragmática descendente estabiliza eje respiratorio y activa conexión gravitacional",ic:"breath",br:{in:4,h1:1,ex:3,h2:0}},
{l:"Gravitación Consciente",r:"30–80s",s:30,e:80,k:"Peso abajo. Gravedad trabaja. Solo suelta.",i:"Mantén la respiración descendente. Siente cómo tu peso cae naturalmente hacia la pelvis. Deja que la gravedad haga el trabajo. Relaja hombros — suéltalos. Relaja cara — mandíbula y frente. Cada parte que relajas te ancla más. No hagas nada nuevo — solo sigue soltando peso hacia abajo con cada exhalación.",sc:"Relajación descendente progresiva activa sistema propioceptivo de seguridad gravitacional",ic:"mind",br:{in:4,h1:1,ex:3,h2:0}},
{l:"Expansión desde la Raíz",r:"80–120s",s:80,e:120,k:"Desde la base, expándete. Sin moverte. Más grande.",i:"Desde esa base anclada, siente tu presencia expandirse sutilmente — 1 cm hacia atrás, hacia los lados, hacia arriba. No es movimiento físico, es intención. Siente tu espalda ocupar más espacio. Hombros se abren sin moverse. Mantén con cada respiración. Abre los ojos: estable y expandido.",sc:"Expansión propioceptiva interna genera ondas alfa asociadas con calma alerta y creatividad",ic:"mind",br:{in:4,h1:1,ex:3,h2:0}}]},

/* ═══ #12 NEURAL ASCENSION ═══
   Objetivo: Elevar estado mental desde el cuerpo hacia claridad y perspectiva
   Lógica: Ola vertical conecta eje → cruce bilateral integra → perspectiva meta-cognitiva
   Respiración 4-4 suave como ola constante de ida y vuelta */
{id:12,n:"Neural Ascension",ct:"Protocolo",d:120,sb:"Ascenso mental y claridad",tg:"NA",cl:"#0D9488",int:"enfoque",dif:2,
ph:[{l:"Ola Vertical",r:"0–30s",s:0,e:30,k:"Aire sube pelvis a cabeza. Baja cabeza a pelvis.",i:"Inhala 4 segundos imaginando que el aire sube desde la pelvis hasta la coronilla como una ola ascendente. Exhala 4 segundos — la ola desciende de cabeza a pelvis. 3 ciclos completos. Siente el eje vertical activarse. No fuerces la imagen — solo sigue el movimiento interno con cada respiración.",sc:"Visualización de flujo vertical integra eje mente-cuerpo y conecta sistema nervioso de arriba a abajo",ic:"breath",br:{in:4,h1:0,ex:4,h2:0}},
{l:"Cruce Interhemisférico",r:"30–80s",s:30,e:80,k:"Mano al pecho opuesto. Siente. Cruza. Conecta.",i:"Mano derecha sobre pecho izquierdo. Siente el latido 10 segundos. Cambia: mano izquierda sobre costilla derecha 10 segundos. Repite el cruce 2 veces más. Respira al ritmo de ola ascendente-descendente. No analices — solo siente cada contacto cruzado. Los hemisferios se comunican.",sc:"Cruce bilateral forzado activa comunicación interhemisférica. Mejora integración cognitiva y creatividad",ic:"body",br:{in:4,h1:0,ex:4,h2:0}},
{l:"Perspectiva Elevada",r:"80–120s",s:80,e:120,k:"Conciencia sube sobre tu cabeza. Observa desde ahí.",i:"Cierra los ojos. Respira suavemente con la ola. Imagina que tu punto de conciencia sube 5 centímetros por encima de tu cabeza. Observa todo desde ahí arriba. Los problemas se ven más pequeños. Las soluciones más claras. Mantén la perspectiva 40 segundos. Abre los ojos trayendo esa claridad.",sc:"Meta-cognición vertical activa red de modo por defecto en modo expansivo. Genera perspectiva y distancia",ic:"mind",br:{in:4,h1:0,ex:4,h2:0}}]},

/* ═══ #13 PROTOCOLO OMEGA ═══
   Objetivo: Realineación neuronal completa. 6 fases para reset profundo.
   Lógica: Silencio → contacto dual → reset bilateral → expansión → micro-pulso → meta-conciencia
   Flujo continuo donde cada fase construye sobre la anterior sin ruptura */
{id:13,n:"Protocolo OMEGA",ct:"Protocolo",d:120,sb:"Realineación neuronal completa",tg:"\u03A9",cl:"#0D9488",int:"reset",dif:3,
ph:[{l:"Vacío Inicial",r:"0–18s",s:0,e:18,k:"Apaga todo. Vacío interior. Silencio absoluto.",i:"Inhala 4 segundos. Exhala 6 segundos. Sostén vacío 2 segundos. Di internamente: 'Apago todo.' Repite el ciclo. El vacío entre exhalación e inhalación es donde tu sistema se resetea. No llenes el silencio.",sc:"Apnea post-exhalatoria inhibe amígdala y reduce actividad del circuito de alarma central",ic:"breath",br:{in:4,h1:0,ex:6,h2:2}},
{l:"Pulso del Núcleo",r:"18–33s",s:18,e:33,k:"Dos manos. Pecho y ombligo. Dos pulsos conectados.",i:"Sin romper el ritmo respiratorio, coloca mano derecha en pecho, izquierda en ombligo. Siente ambos puntos simultáneamente. Percibe la distancia entre ellos. Nota tu latido — cada latido es tu sistema funcionando. Solo siente, no analices.",sc:"Atención bi-focal genera coherencia entre corazón y sistema nervioso entérico (cerebro intestinal)",ic:"body",br:{in:4,h1:0,ex:6,h2:2}},
{l:"Recalibración Bilateral",r:"33–55s",s:33,e:55,k:"Ojos en cruz. Sonido imaginario. Recalibra.",i:"Mantén la respiración. Mueve solo los ojos: derecha 3s, izquierda 3s, arriba 3s, abajo 3s. Ahora imagina un sonido suave moviéndose de oreja a oreja. La combinación recalibra redes bilaterales. Respira suave todo el tiempo.",sc:"Estimulación bilateral visual+auditiva activa procesamiento similar al sueño REM. Reset profundo",ic:"focus",br:null},
{l:"Expansión Silenciosa",r:"55–78s",s:55,e:78,k:"Tu cuerpo se expande 1 cm. Límites difusos.",i:"Sin moverte, siente que tu cuerpo se expande 1 centímetro en todas direcciones. Tus límites físicos se difuminan suavemente. No fuerces — solo permite. Respira suave. Tu percepción del espacio cambia. El mundo se siente más amplio.",sc:"Expansión propioceptiva activa red de percepción espacial y desactiva hipervigilancia",ic:"mind",br:null},
{l:"Micro-pulso Resonante",r:"78–100s",s:78,e:100,k:"Dedos contra pulgares. 8 pulsos. Sincronización.",i:"Con manos abiertas, pulsa dedos contra pulgares: 8 pulsos en 8 segundos al 10% de fuerza. Descansa 2 segundos. Repite una vez. Este ritmo micro-fino sincroniza tu sistema somatosensorial completo. Respira sin alterar el pulso.",sc:"Sincronización somatosensorial rítmica genera coherencia neural entre todas las cortezas cerebrales",ic:"body",br:null},
{l:"Ascenso Omega",r:"100–120s",s:100,e:120,k:"Sobre tu cabeza. Silencio. Claridad absoluta.",i:"Cierra los ojos. Tu conciencia sube 5-7 centímetros sobre tu cabeza. El ruido queda debajo. Aquí arriba: solo silencio y claridad. Mantén 20 segundos. Respira suave. Abre los ojos lentamente trayendo esta calma. Tú decides qué entra a tu mente ahora.",sc:"Estado de observador puro. Máxima activación de corteza prefrontal medial. Meta-conciencia",ic:"mind",br:null}]},

/* ═══ #14 PROTOCOLO OMNIA ═══
   Objetivo: Activación humana total. 7 fases para rendimiento máximo.
   Lógica: Silencio → presencia dual → cruce triple → ola interna → eje central → expansión → sello
   Cada fase amplifica la anterior sin ruptura. El protocolo más avanzado del sistema. */
{id:14,n:"Protocolo OMNIA",ct:"Protocolo",d:120,sb:"Activación Humana Total",tg:"\u221E",cl:"#0D9488",int:"energia",dif:3,
ph:[{l:"Golpe de Silencio",r:"0–12s",s:0,e:12,k:"Silencio total. Apago todo. Cero ruido mental.",i:"Inhala 4 segundos. Exhala 6 segundos. Sostén vacío 2 segundos. Di internamente: 'Apago todo.' El silencio es el punto de partida. Sin él, nada funciona. Quédate en el vacío un momento más.",sc:"Reset neural completo. Silencio reduce actividad del córtex prefrontal lateral para recalibrar base",ic:"breath",br:{in:4,h1:0,ex:6,h2:2}},
{l:"Presencia Doble",r:"12–27s",s:12,e:27,k:"Pecho y abdomen. Dos puntos. Doble presencia.",i:"Sin romper el ritmo, mano derecha en pecho, izquierda en abdomen. Siente ambos puntos simultáneamente. ¿Cuál se mueve más? Esta doble atención entrena tu ínsula cerebral. 15 segundos de pura presencia corporal.",sc:"Interocepción dual activa ínsula y precúneo — centros de conciencia corporal y autoconciencia",ic:"body",br:{in:4,h1:0,ex:6,h2:2}},
{l:"Cruce Neural Triple",r:"27–47s",s:27,e:47,k:"Ojos + sonido imaginario + dedos. Triple canal.",i:"Simultáneamente: mueve ojos en 4 direcciones (3s cada una), imagina un sonido de oreja a oreja, mantén meñiques al 15% de tensión. Tres canales sensoriales a la vez. Respira normalmente. No importa si no es perfecto — el intento ya activa las redes neurales.",sc:"Triple sincronización sensorial simultánea fuerza integración neural máxima entre cortezas",ic:"focus",br:null},
{l:"Ola Ascendente",r:"47–67s",s:47,e:67,k:"Calor que sube. Pies a cabeza. Lento, continuo.",i:"Cierra los ojos. Siente una ola de calor que nace en los pies y sube lentamente: pantorrillas, rodillas, muslos, abdomen, pecho, cuello, cabeza. No la fuerces — solo sigue su recorrido natural durante 20 segundos. Cuando llega arriba, deja que se disipe suavemente. Respira al ritmo que ya tienes.",sc:"Ola propioceptiva ascendente activa red frontoparietal de atención sostenida. Integración corporal total",ic:"mind",br:null},
{l:"Eje Central",r:"67–92s",s:67,e:92,k:"Línea dorada sacro a coronilla. Brilla más fuerte.",i:"Imagina una línea dorada desde tu sacro hasta la coronilla. Un láser estable y brillante. Inhala 4 segundos — la línea brilla más. Exhala 6 — se estabiliza. Este eje te mantiene erguido, centrado e inquebrantable durante 25 segundos.",sc:"Eje propioceptivo vertical genera presencia somática total y alineación del sistema vestibular",ic:"mind",br:{in:4,h1:0,ex:6,h2:0}},
{l:"Expansión del Campo",r:"92–112s",s:92,e:112,k:"Tu presencia se expande. Sin límites. Luminoso.",i:"Tu conciencia se expande 20-40 centímetros alrededor de tu cuerpo. Los límites de tu presencia se extienden más allá de tu piel. No estás solo dentro — tu campo abarca todo a tu alrededor. Luminoso. Expandido. Presente. Respira suave y mantén la expansión.",sc:"Metaestado expandido asociado con flow, rendimiento máximo y creatividad óptima",ic:"mind",br:null},
{l:"Sello OMNIA",r:"112–120s",s:112,e:120,k:"Estoy encendido. Ojos abiertos. A conquistar.",i:"Di internamente con absoluta convicción: 'Estoy encendido.' Inhala una última vez profundamente. Abre los ojos lentamente con la exhalación. Mira el mundo como si lo vieras por primera vez. Lleva toda esta activación contigo. Este es tu estado natural.",sc:"Sello de activación neural. Declaración intencional consolida el estado alcanzado y apertura sensorial",ic:"focus",br:null}]}
];

const CATS=["Reset","Activación","Protocolo"];const LVL=[{n:"INICIADO",m:0,mx:1,c:"#94A3B8"},{n:"OPERADOR",m:1,mx:10,c:"#6366F1"},{n:"EJECUTOR",m:10,mx:25,c:"#059669"},{n:"ESTRATEGA",m:25,mx:50,c:"#D97706"},{n:"COMANDANTE",m:50,mx:100,c:"#DC2626"},{n:"ARQUITECTO",m:100,mx:999,c:"#7C3AED"}];

export { P, CATS, LVL };
export function gL(s){let l=LVL[0];for(const v of LVL)if(s>=v.m)l=v;return l;}
export function lvPct(s){const l=gL(s);if(s>=l.mx)return 100;return Math.round(((s-l.m)/(l.mx-l.m))*100);}
export function nxtLv(s){const i=LVL.findIndex(l=>l.n===gL(s).n);return i<LVL.length-1?LVL[i+1]:null;}
export const DN=["L","M","X","J","V","S","D"];
export const DIF_LABELS=["Básico","Intermedio","Avanzado"];