import { P, DN } from './protocols';
import { DAILY_PHRASES } from './constants';

function getDailyIgn(st){const d=new Date();const seed=d.getFullYear()*1000+d.getMonth()*50+d.getDate();const h=d.getHours();const lastMood=(st.moodLog||[]).slice(-1)[0]?.mood||3;let pool=P;if(h<10)pool=P.filter(p=>p.int==="calma"||p.int==="energia");else if(h<15)pool=P.filter(p=>p.int==="enfoque");else if(h<19)pool=P.filter(p=>p.int==="enfoque"||p.int==="reset");else pool=P.filter(p=>p.int==="calma"||p.int==="reset");if(lastMood<=2)pool=pool.filter(p=>p.dif<=2);const pick=pool[seed%pool.length]||P[0];const phrase=DAILY_PHRASES[seed%DAILY_PHRASES.length];return{proto:pick,phrase};}

function genIns(st){const r=[];if(st.totalSessions>0){const cG=st.coherencia-64;if(cG>10)r.push({t:"up",x:`Enfoque +${cG} puntos desde el inicio.`});const rG=st.resiliencia-66;if(rG>5)r.push({t:"up",x:`Calma sistémica +${rG}%.`});if(st.streak>=3)r.push({t:"fire",x:`${st.streak} días consecutivos. El hábito se consolida.`});if(st.totalTime>0)r.push({t:"star",x:`${Math.round(st.totalTime/60)} minutos invertidos en rendimiento.`});const ml=st.moodLog||[];if(ml.length>=3){const a=ml.slice(-3).reduce((a,m)=>a+m.mood,0)/3;if(a>=4)r.push({t:"up",x:"Tendencia emocional ascendente."});if(a<=2)r.push({t:"alert",x:"Tensión elevada detectada. Prioriza sesiones de Calma."});
  // Hour pattern detection
  const hrs=st.history?.slice(-10).map(h=>new Date(h.ts).getHours())||[];if(hrs.length>=5){const counts={};hrs.forEach(h=>{const b=Math.floor(h/3)*3;counts[b]=(counts[b]||0)+1;});const peak=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];if(peak&&peak[1]>=3){const peakH=parseInt(peak[0]);const now=new Date().getHours();if(Math.abs(now-peakH)<=2&&st.todaySessions===0)r.push({t:"rec",x:`Tu hora pico es ${peakH}:00-${peakH+3}:00. Aprovéchala ahora.`});}}
  }if(st.history?.length>=3){const l3=st.history.slice(-3);if(l3.every(h=>h.p===l3[0].p)){const o=P.find(p=>p.n!==l3[0].p);if(o)r.push({t:"rec",x:`Diversifica: prueba ${o.n}.`});}}}const h=new Date().getHours();if(!r.find(x=>x.t==="rec"))r.push({t:"rec",x:h<12?"Reset Ejecutivo ideal para la mañana.":h<17?"Protocolo OMEGA para la tarde.":"Reinicio Parasimpático para cerrar el día."});if(!r.length)r.push({t:"star",x:"Tu primera ignición te espera."});return r;}

function smartSuggest(st){const h=new Date().getHours();const lastMood=(st.moodLog||[]).slice(-1)[0]?.mood||3;const lastP=(st.history||[]).slice(-1)[0]?.p||"";let intent="calma";if(h>=6&&h<10)intent=lastMood<=2?"reset":"energia";else if(h>=10&&h<14)intent="enfoque";else if(h>=14&&h<18)intent=lastMood<=2?"calma":"enfoque";else intent="calma";const opts=P.filter(p=>p.int===intent&&p.n!==lastP);return opts.length?opts[Math.floor(Math.random()*opts.length)]:P[0];}

function getRecords(st){const h=st.history||[];const ml=st.moodLog||[];const bestStreak=Math.max(st.streak,...[st.streak]);const maxC=h.length?Math.max(...h.map(x=>x.c)):st.coherencia;const protos={};h.forEach(x=>{protos[x.p]=(protos[x.p]||0)+1;});const topProto=Object.entries(protos).sort((a,b)=>b[1]-a[1])[0];const hours=h.map(x=>new Date(x.ts).getHours()).filter(x=>x>0);const earliest=hours.length?Math.min(...hours):null;return{bestStreak,maxC,topProto:topProto?{n:topProto[0],c:topProto[1]}:null,earliest};}

function groupHist(h){const n=new Date();const td=n.toDateString();const yd=new Date(Date.now()-864e5).toDateString();const g={hoy:[],ayer:[],antes:[]};for(const x of h){const d=new Date(x.ts).toDateString();if(d===td)g.hoy.push(x);else if(d===yd)g.ayer.push(x);else g.antes.push(x);}return g;}

export { getDailyIgn, genIns, smartSuggest, getRecords, groupHist };
